services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql  # Исправлено: добавил /data
    networks:
      - server  # Изменено: с "server" на "carsensor_network"

  server:
    build: ./server
    container_name: server
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - server

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
    environment:
      NEXT_PUBLIC_API_URL: http://server:3001
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - server

  parser:
    build: ./parser
    container_name: parser
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PARSER_INTERVAL_HOURS: 1
      API_URL: http://server:3001
    depends_on:
      - postgres
      - server
    networks:
      - server

volumes:
  postgres_data:

networks:
  server:
    driver: bridge